
version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backup-backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: backup-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped
