version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backup-backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: backup-frontend
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    driver: bridge
